CREATE TABLE cards (
    id            text PRIMARY KEY,
    artist        text DEFAULT '' ,
    border        text DEFAULT '' ,
    cmc           text DEFAULT '' ,
    colorIdentity text DEFAULT '' ,
    colors        text DEFAULT '' ,
    flavor        text DEFAULT '' ,
    foreignNames  text DEFAULT '' ,
    hand          text DEFAULT '' ,
    imageName     text DEFAULT '' ,
    layout        text DEFAULT '' ,
    legalities    text DEFAULT '' ,
    life          text DEFAULT '' ,
    loyalty       text DEFAULT '' ,
    manaCost      text DEFAULT '' ,
    mciNumber     text DEFAULT '' ,
    multiverseid  text DEFAULT '' ,
    name          text DEFAULT '' ,
    names         text DEFAULT '' ,
    number        text DEFAULT '' ,
    originalText  text DEFAULT '' ,
    originalType  text DEFAULT '' ,
    power         text DEFAULT '' ,
    printings     text DEFAULT '' ,
    rarity        text DEFAULT '' ,
    releaseDate   text DEFAULT '' ,
    reserved      text DEFAULT '' ,
    rulings       text DEFAULT '' ,
    source        text DEFAULT '' ,
    starter       text DEFAULT '' ,
    subtypes      text DEFAULT '' ,
    supertypes    text DEFAULT '' ,
    text          text DEFAULT '' ,
    timeshifted   text DEFAULT '' ,
    toughness     text DEFAULT '' ,
    type          text DEFAULT '' ,
    types         text DEFAULT '' ,
    variations    text DEFAULT '' ,
    watermark     text DEFAULT '' ,
    setcode       text DEFAULT ''
);

CREATE TABLE sets (
    code               text PRIMARY KEY,
    alternativeNames   text DEFAULT '' ,
    name               text DEFAULT '' ,
    gathererCode       text DEFAULT '' ,
    oldCode            text DEFAULT '' ,
    magicCardsInfoCode text DEFAULT '' ,
    magicRaritiesCodes text DEFAULT '' ,
    releaseDate        date DEFAULT null ,
    border             text DEFAULT '' ,
    type               text DEFAULT '' ,
    block              text DEFAULT '' ,
    onlineOnly         text DEFAULT '' ,
    booster            text DEFAULT '' ,
    translations       text DEFAULT '' ,
    mkm_name           text DEFAULT '' ,
    mkm_id             text DEFAULT ''
);

