CREATE TABLE cards (
    id text PRIMARY KEY,
    layout text DEFAULT '' ,
    name text DEFAULT '' ,
    names text DEFAULT '',
    manaCost text DEFAULT '' ,
    cmc text DEFAULT '' ,
    colors text DEFAULT '' ,
    colorIdentity text DEFAULT '' ,
    type text DEFAULT '' ,
    supertypes text DEFAULT '',
    types text DEFAULT '' ,
    subtypes text DEFAULT '',
    rarity text DEFAULT '' ,
    text text DEFAULT '' ,
    flavor text DEFAULT '' ,
    artist text DEFAULT '' ,
    number text DEFAULT '' ,
    power text DEFAULT '' ,
    toughness text DEFAULT '' ,
    loyalty text DEFAULT '',
    multiverseid text DEFAULT '' ,
    variations text DEFAULT '',
    imageName text DEFAULT '' ,
    watermark text DEFAULT '',
    border text DEFAULT '',
    timeshifted text DEFAULT '',
    hand text DEFAULT '',
    life text DEFAULT '',
    reserved text DEFAULT '' ,
    releaseDate text DEFAULT '' ,
    starter text DEFAULT '' ,
    mciNumber text DEFAULT '' ,
    rulings text DEFAULT '' ,
    foreignNames text DEFAULT '' ,
    printings text DEFAULT '' ,
    originalText text DEFAULT '' ,
    originalType text DEFAULT '' ,
    legalities text DEFAULT '' ,
    source text DEFAULT '' ,
    setcode text DEFAULT ''
);

CREATE TABLE sets (
    code               text PRIMARY KEY,
    alternativeNames   text DEFAULT '' ,
    name               text DEFAULT '' ,
    gathererCode       text DEFAULT '' ,
    oldCode            text DEFAULT '' ,
    magicCardsInfoCode text DEFAULT '' ,
    magicRaritiesCodes text DEFAULT '' ,
    releaseDate        text DEFAULT '' ,
    border             text DEFAULT '' ,
    type               text DEFAULT '' ,
    block              text DEFAULT '' ,
    onlineOnly         text DEFAULT '' ,
    booster            text DEFAULT '' ,
    translations       text DEFAULT '' ,
    mkm_name           text DEFAULT '' ,
    mkm_id             text DEFAULT ''
);

