./10E.sh 1> ./10E.shstdout.log 2> ./10E.shstderr.log &
./2ED.sh 1> ./2ED.shstdout.log 2> ./2ED.shstderr.log &
./3ED.sh 1> ./3ED.shstdout.log 2> ./3ED.shstderr.log &
./4ED.sh 1> ./4ED.shstdout.log 2> ./4ED.shstderr.log &
./5DN.sh 1> ./5DN.shstdout.log 2> ./5DN.shstderr.log &
./5ED.sh 1> ./5ED.shstdout.log 2> ./5ED.shstderr.log &
./6ED.sh 1> ./6ED.shstdout.log 2> ./6ED.shstderr.log &
./7ED.sh 1> ./7ED.shstdout.log 2> ./7ED.shstderr.log &
./8ED.sh 1> ./8ED.shstdout.log 2> ./8ED.shstderr.log &
./9ED.sh 1> ./9ED.shstdout.log 2> ./9ED.shstderr.log &
./AER.sh 1> ./AER.shstdout.log 2> ./AER.shstderr.log &
./AKH.sh 1> ./AKH.shstdout.log 2> ./AKH.shstderr.log &
./ALA.sh 1> ./ALA.shstdout.log 2> ./ALA.shstderr.log &
./ALL.sh 1> ./ALL.shstdout.log 2> ./ALL.shstderr.log &
./APC.sh 1> ./APC.shstdout.log 2> ./APC.shstderr.log &
./ARB.sh 1> ./ARB.shstdout.log 2> ./ARB.shstderr.log &
./ARC.sh 1> ./ARC.shstdout.log 2> ./ARC.shstderr.log &
./ARN.sh 1> ./ARN.shstdout.log 2> ./ARN.shstderr.log &
./ATH.sh 1> ./ATH.shstdout.log 2> ./ATH.shstderr.log &
./ATQ.sh 1> ./ATQ.shstdout.log 2> ./ATQ.shstderr.log &
./AVR.sh 1> ./AVR.shstdout.log 2> ./AVR.shstderr.log &
./BFZ.sh 1> ./BFZ.shstdout.log 2> ./BFZ.shstderr.log &
./BNG.sh 1> ./BNG.shstdout.log 2> ./BNG.shstderr.log &
./BOK.sh 1> ./BOK.shstdout.log 2> ./BOK.shstderr.log &
./BRB.sh 1> ./BRB.shstdout.log 2> ./BRB.shstderr.log &
./BTD.sh 1> ./BTD.shstdout.log 2> ./BTD.shstderr.log &
./C13.sh 1> ./C13.shstdout.log 2> ./C13.shstderr.log &
./C14.sh 1> ./C14.shstdout.log 2> ./C14.shstderr.log &
./C15.sh 1> ./C15.shstdout.log 2> ./C15.shstderr.log &
./C16.sh 1> ./C16.shstdout.log 2> ./C16.shstderr.log &
./CED.sh 1> ./CED.shstdout.log 2> ./CED.shstderr.log &
./CEI.sh 1> ./CEI.shstdout.log 2> ./CEI.shstderr.log &
./CHK.sh 1> ./CHK.shstdout.log 2> ./CHK.shstderr.log &
./CHR.sh 1> ./CHR.shstdout.log 2> ./CHR.shstderr.log &
./CM1.sh 1> ./CM1.shstdout.log 2> ./CM1.shstderr.log &
./CMA.sh 1> ./CMA.shstdout.log 2> ./CMA.shstderr.log &
./CMD.sh 1> ./CMD.shstdout.log 2> ./CMD.shstderr.log &
./CN2.sh 1> ./CN2.shstdout.log 2> ./CN2.shstderr.log &
./CNS.sh 1> ./CNS.shstdout.log 2> ./CNS.shstderr.log &
./CON.sh 1> ./CON.shstdout.log 2> ./CON.shstderr.log &
./CPK.sh 1> ./CPK.shstdout.log 2> ./CPK.shstderr.log &
./CSP.sh 1> ./CSP.shstdout.log 2> ./CSP.shstderr.log &
./CST.sh 1> ./CST.shstdout.log 2> ./CST.shstderr.log &
./DD2.sh 1> ./DD2.shstdout.log 2> ./DD2.shstderr.log &
./DD3_DVD.sh 1> ./DD3_DVD.shstdout.log 2> ./DD3_DVD.shstderr.log &
./DD3_EVG.sh 1> ./DD3_EVG.shstdout.log 2> ./DD3_EVG.shstderr.log &
./DD3_GVL.sh 1> ./DD3_GVL.shstdout.log 2> ./DD3_GVL.shstderr.log &
./DD3_JVC.sh 1> ./DD3_JVC.shstdout.log 2> ./DD3_JVC.shstderr.log &
./DDC.sh 1> ./DDC.shstdout.log 2> ./DDC.shstderr.log &
./DDD.sh 1> ./DDD.shstdout.log 2> ./DDD.shstderr.log &
./DDE.sh 1> ./DDE.shstdout.log 2> ./DDE.shstderr.log &
./DDF.sh 1> ./DDF.shstdout.log 2> ./DDF.shstderr.log &
./DDG.sh 1> ./DDG.shstdout.log 2> ./DDG.shstderr.log &
./DDH.sh 1> ./DDH.shstdout.log 2> ./DDH.shstderr.log &
./DDI.sh 1> ./DDI.shstdout.log 2> ./DDI.shstderr.log &
./DDJ.sh 1> ./DDJ.shstdout.log 2> ./DDJ.shstderr.log &
./DDK.sh 1> ./DDK.shstdout.log 2> ./DDK.shstderr.log &
./DDL.sh 1> ./DDL.shstdout.log 2> ./DDL.shstderr.log &
./DDM.sh 1> ./DDM.shstdout.log 2> ./DDM.shstderr.log &
./DDN.sh 1> ./DDN.shstdout.log 2> ./DDN.shstderr.log &
./DDO.sh 1> ./DDO.shstdout.log 2> ./DDO.shstderr.log &
./DDP.sh 1> ./DDP.shstdout.log 2> ./DDP.shstderr.log &
./DDQ.sh 1> ./DDQ.shstdout.log 2> ./DDQ.shstderr.log &
./DDR.sh 1> ./DDR.shstdout.log 2> ./DDR.shstderr.log &
./DDS.sh 1> ./DDS.shstdout.log 2> ./DDS.shstderr.log &
./DGM.sh 1> ./DGM.shstdout.log 2> ./DGM.shstderr.log &
./DIS.sh 1> ./DIS.shstdout.log 2> ./DIS.shstderr.log &
./DKA.sh 1> ./DKA.shstdout.log 2> ./DKA.shstderr.log &
./DKM.sh 1> ./DKM.shstdout.log 2> ./DKM.shstderr.log &
./DPA.sh 1> ./DPA.shstdout.log 2> ./DPA.shstderr.log &
./DRB.sh 1> ./DRB.shstdout.log 2> ./DRB.shstderr.log &
./DRK.sh 1> ./DRK.shstdout.log 2> ./DRK.shstderr.log &
./DST.sh 1> ./DST.shstdout.log 2> ./DST.shstderr.log &
./DTK.sh 1> ./DTK.shstdout.log 2> ./DTK.shstderr.log &
./E01.sh 1> ./E01.shstdout.log 2> ./E01.shstderr.log &
./EMA.sh 1> ./EMA.shstdout.log 2> ./EMA.shstderr.log &
./EMN.sh 1> ./EMN.shstdout.log 2> ./EMN.shstderr.log &
./EVE.sh 1> ./EVE.shstdout.log 2> ./EVE.shstderr.log &
./EVG.sh 1> ./EVG.shstdout.log 2> ./EVG.shstderr.log &
./EXO.sh 1> ./EXO.shstdout.log 2> ./EXO.shstderr.log &
./EXP.sh 1> ./EXP.shstdout.log 2> ./EXP.shstderr.log &
./FEM.sh 1> ./FEM.shstdout.log 2> ./FEM.shstderr.log &
./FRF.sh 1> ./FRF.shstdout.log 2> ./FRF.shstderr.log &
./FRF_UGIN.sh 1> ./FRF_UGIN.shstdout.log 2> ./FRF_UGIN.shstderr.log &
./FUT.sh 1> ./FUT.shstdout.log 2> ./FUT.shstderr.log &
./GPT.sh 1> ./GPT.shstdout.log 2> ./GPT.shstderr.log &
./GTC.sh 1> ./GTC.shstdout.log 2> ./GTC.shstderr.log &
./H09.sh 1> ./H09.shstdout.log 2> ./H09.shstderr.log &
./HML.sh 1> ./HML.shstdout.log 2> ./HML.shstderr.log &
./HOP.sh 1> ./HOP.shstdout.log 2> ./HOP.shstderr.log &
./HOU.sh 1> ./HOU.shstdout.log 2> ./HOU.shstderr.log &
./ICE.sh 1> ./ICE.shstdout.log 2> ./ICE.shstderr.log &
./INV.sh 1> ./INV.shstdout.log 2> ./INV.shstderr.log &
./ISD.sh 1> ./ISD.shstdout.log 2> ./ISD.shstderr.log &
./ITP.sh 1> ./ITP.shstdout.log 2> ./ITP.shstderr.log &
./JOU.sh 1> ./JOU.shstdout.log 2> ./JOU.shstderr.log &
./JUD.sh 1> ./JUD.shstdout.log 2> ./JUD.shstderr.log &
./KLD.sh 1> ./KLD.shstdout.log 2> ./KLD.shstderr.log &
./KTK.sh 1> ./KTK.shstdout.log 2> ./KTK.shstderr.log &
./LEA.sh 1> ./LEA.shstdout.log 2> ./LEA.shstderr.log &
./LEB.sh 1> ./LEB.shstdout.log 2> ./LEB.shstderr.log &
./LEG.sh 1> ./LEG.shstdout.log 2> ./LEG.shstderr.log &
./LGN.sh 1> ./LGN.shstdout.log 2> ./LGN.shstderr.log &
./LRW.sh 1> ./LRW.shstdout.log 2> ./LRW.shstderr.log &
./M10.sh 1> ./M10.shstdout.log 2> ./M10.shstderr.log &
./M11.sh 1> ./M11.shstdout.log 2> ./M11.shstderr.log &
./M12.sh 1> ./M12.shstdout.log 2> ./M12.shstderr.log &
./M13.sh 1> ./M13.shstdout.log 2> ./M13.shstderr.log &
./M14.sh 1> ./M14.shstdout.log 2> ./M14.shstderr.log &
./M15.sh 1> ./M15.shstdout.log 2> ./M15.shstderr.log &
./MBS.sh 1> ./MBS.shstdout.log 2> ./MBS.shstderr.log &
./MD1.sh 1> ./MD1.shstdout.log 2> ./MD1.shstderr.log &
./ME2.sh 1> ./ME2.shstdout.log 2> ./ME2.shstderr.log &
./ME3.sh 1> ./ME3.shstdout.log 2> ./ME3.shstderr.log &
./ME4.sh 1> ./ME4.shstdout.log 2> ./ME4.shstderr.log &
./MED.sh 1> ./MED.shstdout.log 2> ./MED.shstderr.log &
./MGB.sh 1> ./MGB.shstdout.log 2> ./MGB.shstderr.log &
./MIR.sh 1> ./MIR.shstdout.log 2> ./MIR.shstderr.log &
./MM2.sh 1> ./MM2.shstdout.log 2> ./MM2.shstderr.log &
./MM3.sh 1> ./MM3.shstdout.log 2> ./MM3.shstderr.log &
./MMA.sh 1> ./MMA.shstdout.log 2> ./MMA.shstderr.log &
./MMQ.sh 1> ./MMQ.shstdout.log 2> ./MMQ.shstderr.log &
./MOR.sh 1> ./MOR.shstdout.log 2> ./MOR.shstderr.log &
./MPS.sh 1> ./MPS.shstdout.log 2> ./MPS.shstderr.log &
./MPS_AKH.sh 1> ./MPS_AKH.shstdout.log 2> ./MPS_AKH.shstderr.log &
./MRD.sh 1> ./MRD.shstdout.log 2> ./MRD.shstderr.log &
./NMS.sh 1> ./NMS.shstdout.log 2> ./NMS.shstderr.log &
./NPH.sh 1> ./NPH.shstdout.log 2> ./NPH.shstderr.log &
./ODY.sh 1> ./ODY.shstdout.log 2> ./ODY.shstderr.log &
./OGW.sh 1> ./OGW.shstdout.log 2> ./OGW.shstderr.log &
./ONS.sh 1> ./ONS.shstdout.log 2> ./ONS.shstderr.log &
./ORI.sh 1> ./ORI.shstdout.log 2> ./ORI.shstderr.log &
./PC2.sh 1> ./PC2.shstdout.log 2> ./PC2.shstderr.log &
./PCA.sh 1> ./PCA.shstdout.log 2> ./PCA.shstderr.log &
./PCY.sh 1> ./PCY.shstdout.log 2> ./PCY.shstderr.log &
./PD2.sh 1> ./PD2.shstdout.log 2> ./PD2.shstderr.log &
./PD3.sh 1> ./PD3.shstdout.log 2> ./PD3.shstderr.log &
./PLC.sh 1> ./PLC.shstdout.log 2> ./PLC.shstderr.log &
./PLS.sh 1> ./PLS.shstdout.log 2> ./PLS.shstderr.log &
./PO2.sh 1> ./PO2.shstdout.log 2> ./PO2.shstderr.log &
./POR.sh 1> ./POR.shstdout.log 2> ./POR.shstderr.log &
./PTK.sh 1> ./PTK.shstdout.log 2> ./PTK.shstderr.log &
./RAV.sh 1> ./RAV.shstdout.log 2> ./RAV.shstderr.log &
./ROE.sh 1> ./ROE.shstdout.log 2> ./ROE.shstderr.log &
./RQS.sh 1> ./RQS.shstdout.log 2> ./RQS.shstderr.log &
./RTR.sh 1> ./RTR.shstdout.log 2> ./RTR.shstderr.log &
./S00.sh 1> ./S00.shstdout.log 2> ./S00.shstderr.log &
./S99.sh 1> ./S99.shstdout.log 2> ./S99.shstderr.log &
./SCG.sh 1> ./SCG.shstdout.log 2> ./SCG.shstderr.log &
./SHM.sh 1> ./SHM.shstdout.log 2> ./SHM.shstderr.log &
./SOI.sh 1> ./SOI.shstdout.log 2> ./SOI.shstderr.log &
./SOK.sh 1> ./SOK.shstdout.log 2> ./SOK.shstderr.log &
./SOM.sh 1> ./SOM.shstdout.log 2> ./SOM.shstderr.log &
./STH.sh 1> ./STH.shstdout.log 2> ./STH.shstderr.log &
./THS.sh 1> ./THS.shstdout.log 2> ./THS.shstderr.log &
./TMP.sh 1> ./TMP.shstdout.log 2> ./TMP.shstderr.log &
./TOR.sh 1> ./TOR.shstdout.log 2> ./TOR.shstderr.log &
./TPR.sh 1> ./TPR.shstdout.log 2> ./TPR.shstderr.log &
./TSB.sh 1> ./TSB.shstdout.log 2> ./TSB.shstderr.log &
./TSP.sh 1> ./TSP.shstdout.log 2> ./TSP.shstderr.log &
./UDS.sh 1> ./UDS.shstdout.log 2> ./UDS.shstderr.log &
./UGL.sh 1> ./UGL.shstdout.log 2> ./UGL.shstderr.log &
./ULG.sh 1> ./ULG.shstdout.log 2> ./ULG.shstderr.log &
./UNH.sh 1> ./UNH.shstdout.log 2> ./UNH.shstderr.log &
./USG.sh 1> ./USG.shstdout.log 2> ./USG.shstderr.log &
./V09.sh 1> ./V09.shstdout.log 2> ./V09.shstderr.log &
./V10.sh 1> ./V10.shstdout.log 2> ./V10.shstderr.log &
./V11.sh 1> ./V11.shstdout.log 2> ./V11.shstderr.log &
./V12.sh 1> ./V12.shstdout.log 2> ./V12.shstderr.log &
./V13.sh 1> ./V13.shstdout.log 2> ./V13.shstderr.log &
./V14.sh 1> ./V14.shstdout.log 2> ./V14.shstderr.log &
./V15.sh 1> ./V15.shstdout.log 2> ./V15.shstderr.log &
./V16.sh 1> ./V16.shstdout.log 2> ./V16.shstderr.log &
./VAN.sh 1> ./VAN.shstdout.log 2> ./VAN.shstderr.log &
./VIS.sh 1> ./VIS.shstdout.log 2> ./VIS.shstderr.log &
./VMA.sh 1> ./VMA.shstdout.log 2> ./VMA.shstderr.log &
./W16.sh 1> ./W16.shstdout.log 2> ./W16.shstderr.log &
./W17.sh 1> ./W17.shstdout.log 2> ./W17.shstderr.log &
./WTH.sh 1> ./WTH.shstdout.log 2> ./WTH.shstderr.log &
./WWK.sh 1> ./WWK.shstdout.log 2> ./WWK.shstderr.log &
./ZEN.sh 1> ./ZEN.shstdout.log 2> ./ZEN.shstderr.log &
./p15A.sh 1> ./p15A.shstdout.log 2> ./p15A.shstderr.log &
./p2HG.sh 1> ./p2HG.shstdout.log 2> ./p2HG.shstderr.log &
./pALP.sh 1> ./pALP.shstdout.log 2> ./pALP.shstderr.log &
./pARL.sh 1> ./pARL.shstdout.log 2> ./pARL.shstderr.log &
./pCEL.sh 1> ./pCEL.shstdout.log 2> ./pCEL.shstderr.log &
./pCMP.sh 1> ./pCMP.shstdout.log 2> ./pCMP.shstderr.log &
./pDRC.sh 1> ./pDRC.shstdout.log 2> ./pDRC.shstderr.log &
./pELP.sh 1> ./pELP.shstdout.log 2> ./pELP.shstderr.log &
./pFNM.sh 1> ./pFNM.shstdout.log 2> ./pFNM.shstderr.log &
./pGPX.sh 1> ./pGPX.shstdout.log 2> ./pGPX.shstderr.log &
./pGRU.sh 1> ./pGRU.shstdout.log 2> ./pGRU.shstderr.log &
./pGTW.sh 1> ./pGTW.shstdout.log 2> ./pGTW.shstderr.log &
./pHHO.sh 1> ./pHHO.shstdout.log 2> ./pHHO.shstderr.log &
./pJGP.sh 1> ./pJGP.shstdout.log 2> ./pJGP.shstderr.log &
./pLGM.sh 1> ./pLGM.shstdout.log 2> ./pLGM.shstderr.log &
./pLPA.sh 1> ./pLPA.shstdout.log 2> ./pLPA.shstderr.log &
./pMEI.sh 1> ./pMEI.shstdout.log 2> ./pMEI.shstderr.log &
./pMGD.sh 1> ./pMGD.shstdout.log 2> ./pMGD.shstderr.log &
./pMPR.sh 1> ./pMPR.shstdout.log 2> ./pMPR.shstderr.log &
./pPOD.sh 1> ./pPOD.shstdout.log 2> ./pPOD.shstderr.log &
./pPRE.sh 1> ./pPRE.shstdout.log 2> ./pPRE.shstderr.log &
./pPRO.sh 1> ./pPRO.shstdout.log 2> ./pPRO.shstderr.log &
./pREL.sh 1> ./pREL.shstdout.log 2> ./pREL.shstderr.log &
./pSUM.sh 1> ./pSUM.shstdout.log 2> ./pSUM.shstderr.log &
./pSUS.sh 1> ./pSUS.shstdout.log 2> ./pSUS.shstderr.log &
./pWCQ.sh 1> ./pWCQ.shstdout.log 2> ./pWCQ.shstderr.log &
./pWOR.sh 1> ./pWOR.shstdout.log 2> ./pWOR.shstderr.log &
./pWOS.sh 1> ./pWOS.shstdout.log 2> ./pWOS.shstderr.log &
./pWPN.sh 1> ./pWPN.shstdout.log 2> ./pWPN.shstderr.log &
